RMET-439 File Viewer Plugin ::: As iOS Developer I can open a document
OutSystems/cordova-outsystems-fileviewer pull request #3
Opened 2021-02-02 13:50 UTC by CarlsCorrea

## Description

Implementetion of the iOS side of the plugin

## Context

Closes: https://outsystemsrd.atlassian.net/browse/RMET-439

## Type of changes

- [ ] Fix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Refactor (cosmetic changes)
- [ ] Breaking change (change that would cause existing functionality to not work as expected)

## Platforms affected
- [ ] Android
- [x] iOS
- [ ] JavaScript

## Tests

## Screenshots (if appropriate)

## Checklist

- [x] Pull request title follows the format `RNMT-XXXX <title>`
- [x] Code follows code style of this project
- [ ] CHANGELOG.md file is correctly updated
- [x] Changes require an update to the documentation
	- [ ] Documentation has been updated accordingly

2021-02-04 09:11 UTC, vmfo22 commented on plugin.xml
> +      <feature name="CDVFileViewer">
what's the main reason for this name?

2021-02-04 09:20 UTC, CarlsCorrea commented on plugin.xml
> +      <feature name="CDVFileViewer">
Gonçalo told me that this is the correct pattern. Start the file that communicates with the Cordova with CVD

2021-02-04 15:58 UTC, andregrillo approved these changes

2021-02-04 22:13 UTC, vmfo22 requested changes
Nice work @CarlsCorrea! 

Please check my comments

2021-02-04 22:13 UTC, vmfo22 commented on plugin.xml
> +    <dependency url="https://github.com/agoncalvesos/cordova-plugin-add-swift-support" commit="513e43f94ae94ad609d49f24e7dca23a4c358095" id="cordova-plugin-add-swift-support"/>
In the future, we might want to have our own version of swift support

2021-02-04 22:13 UTC, vmfo22 commented on src/ios/CDVFileViewer.swift
> +            try plugin.openDocumentFromLocalPath(url: filePath)
If we are passing as a parameter the file path, shouldn't the var name be `filePath` instead of `url`?

2021-02-04 22:13 UTC, vmfo22 commented on src/ios/CDVFileViewer.swift
> +            try plugin.openDocumentFromLocalPath(url: filePath)
Another question, if the filePath is invalid and we get an error to open the document, how are we sending the result back to JS?

2021-02-04 22:13 UTC, vmfo22 commented on src/ios/CDVFileViewer.swift
> +            try plugin.openDocumentFromLocalPath(url: filePath)
For all use cases, an exception will be thrown?

2021-02-05 10:38 UTC, CarlsCorrea commented on src/ios/CDVFileViewer.swift
> +            try plugin.openDocumentFromLocalPath(url: filePath)
The error thrown in this case will be "The file does not exist". 
We are mapping empty urls and invalid file path.
If for some reason even the url is not empty and the file exists, and not be possible to open, the error will be "Could not open the document".

2021-02-05 10:39 UTC, CarlsCorrea commented on src/ios/CDVFileViewer.swift
> +            try plugin.openDocumentFromLocalPath(url: filePath)
sure, make sense I will change the name of the parameter.

2021-02-05 16:07 UTC, CarlsCorrea commented on plugin.xml
> +    <dependency url="https://github.com/agoncalvesos/cordova-plugin-add-swift-support" commit="513e43f94ae94ad609d49f24e7dca23a4c358095" id="cordova-plugin-add-swift-support"/>
ok, should I create an issue?

2021-02-05 19:08 UTC, vmfo22 commented on src/ios/CDVFileViewer.swift
> +            try plugin.openDocumentFromLocalPath(url: filePath)
Ok, thanks

2021-02-05 19:11 UTC, vmfo22 commented on plugin.xml
> +    <dependency url="https://github.com/agoncalvesos/cordova-plugin-add-swift-support" commit="513e43f94ae94ad609d49f24e7dca23a4c358095" id="cordova-plugin-add-swift-support"/>
Not in the context of this PR. It's for the future. We need to think about having control of this dependency.

2021-02-05 19:39 UTC, CarlsCorrea commented on plugin.xml
> +    <dependency url="https://github.com/agoncalvesos/cordova-plugin-add-swift-support" commit="513e43f94ae94ad609d49f24e7dca23a4c358095" id="cordova-plugin-add-swift-support"/>
ok

2021-02-06 23:17 UTC, vmfo22 commented on src/ios/FileViewerOpenDocument.swift
> +            if success, let filePath = fileLocationURL {
If the download fails, how are we dealing with error?

2021-02-07 22:45 UTC, CarlsCorrea commented on src/ios/FileViewerOpenDocument.swift
> +            if success, let filePath = fileLocationURL {
good point, I need to implement the return of the download error...

2021-02-10 11:42 UTC, vmfo22 approved these changes

2021-02-10 15:58 UTC, merged